### ISSUE TITLE
Error when attempting to run locally

### ISSUE THREAD

**Issue by davidworkman9** [ssr-server/uglifyjs2#1]
I get this error when trying to run meteor locally with uglifyjs2 development turned on in my `package.json` file. I've removed the standard minifier and added this package.
```
While running registerMinifier callback in package ssrwpo:uglifyjs2:
   native: Unexpected string
   at Object.parse (native)
   at new UglifyJSMinifier (packages/ssrwpo:uglifyjs2/plugin.js:59:32)
   at packages/ssrwpo:uglifyjs2/plugin.js:141:10
```

**Comment by davidworkman9** [comment]
Seemed to only be an issue if I've never ran Meteor locally before with this package without `"development": true`. Running without, then running with it got me a lot further. However it's been 20 minutes and about 5 of those minutes it's been stuck at `Starting your app`

**Comment by PEM--** [comment]
Did you init a `package.json`?

This line parses it: https://github.com/ssrwpo/uglifyjs2/blob/master/plugin.js#L59

**Comment by davidworkman9** [comment]
I already had one. For some reason it had to be ran once without development, don't know why but it seems to work now. But as I said it gets stuck at "Starting your app". I gave up after letting it run for an hour, on a brand new macbook pro.

**Comment by PEM--** [comment]
Thanks for the feedback. Pretty weird. It's like Node is hanging up on a file access.

**Comment by davidworkman9** [comment]
Like I said on the [forums](https://forums.meteor.com/t/ssrwpo-uglifyjs2-push-js-minification-a-bit-further/33728), got it working! Thanks!
