### ISSUE TITLE
drop_console: false does not show console in production

### ISSUE THREAD

**Issue by tmpg** [ssr-server/uglifyjs2#8]
drop_console: false does not show console in production. 

```
package.json:
  "uglifyjs2": {
...
    "development": false,
    "drop_console": false
  },
```

Let me know if there is something else I should be doing.

**Comment by PEM--** [comment]
Your usage puzzles me 🤔

**Comment by tmpg** [comment]
I am running a test on my production server. Is there something wrong with it technically?

**Comment by PEM--** [comment]
Check your `package.json`. It seems that you have not set it properly. Here's an extract from the doc:
```
uglifyjs2: {
  ...
  options: {
    ...
    compress: {
      ...
      drop_console: true,
     ...
```

**Comment by tmpg** [comment]
Thanks, I missed the `options` key like a dummy.
